import type { StormReport } from "@/types/storm";

/** Relative dates from a fixed "today" so sample data stays useful. */
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().slice(0, 10);
}

/**
 * Sample Florida storm reports for MVP demo.
 * Covers hail, wind, tornado, severe thunderstorm, and hurricane-related activity.
 */
export const SAMPLE_STORMS: StormReport[] = [
  {
    id: "storm-001",
    type: "hail",
    date: daysAgo(0),
    time: "14:22",
    city: "Orlando",
    zipCode: "32801",
    windSpeedMph: 45,
    hailSizeInches: 1.75,
    lat: 28.5383,
    lng: -81.3792,
    source: "NWS Storm Reports (sample)",
    sourceUrl: "https://www.weather.gov/",
    confidence: "high",
    confidenceScore: 88,
    severity: 82,
    reportCount: 14,
    residentialDensity: 78,
    estimatedPropertyAge: 22,
    description: "Golf-ball sized hail reported across downtown Orlando and College Park.",
    county: "Orange",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-002",
    type: "wind",
    date: daysAgo(0),
    time: "16:05",
    city: "Tampa",
    zipCode: "33602",
    windSpeedMph: 68,
    hailSizeInches: null,
    lat: 27.9506,
    lng: -82.4572,
    source: "ASOS Airport Observation — KTPA (sample)",
    confidence: "verified",
    confidenceScore: 95,
    severity: 75,
    reportCount: 9,
    residentialDensity: 72,
    estimatedPropertyAge: 28,
    description: "Damaging thunderstorm winds near Tampa International; tree and roof damage reported.",
    county: "Hillsborough",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-003",
    type: "tornado",
    date: daysAgo(1),
    time: "18:40",
    city: "Lakeland",
    zipCode: "33801",
    windSpeedMph: 95,
    hailSizeInches: null,
    lat: 28.0395,
    lng: -81.9498,
    source: "NWS Local Storm Report (sample)",
    confidence: "high",
    confidenceScore: 90,
    severity: 92,
    reportCount: 6,
    residentialDensity: 65,
    estimatedPropertyAge: 30,
    description: "EF1 tornado confirmed along US-92 corridor; spotters reported funnel and debris.",
    county: "Polk",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-004",
    type: "severe_thunderstorm",
    date: daysAgo(1),
    time: "15:10",
    city: "Jacksonville",
    zipCode: "32202",
    windSpeedMph: 58,
    hailSizeInches: 0.75,
    lat: 30.3322,
    lng: -81.6557,
    source: "NWS Alert — Severe Thunderstorm Warning (sample)",
    confidence: "high",
    confidenceScore: 85,
    severity: 70,
    reportCount: 11,
    residentialDensity: 70,
    estimatedPropertyAge: 35,
    description: "Severe thunderstorm with nickel hail and 50–60 mph gusts across downtown JAX.",
    county: "Duval",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-005",
    type: "hail",
    date: daysAgo(2),
    time: "13:55",
    city: "Fort Myers",
    zipCode: "33901",
    windSpeedMph: 40,
    hailSizeInches: 1.25,
    lat: 26.6406,
    lng: -81.8723,
    source: "Local news weather desk (sample)",
    confidence: "medium",
    confidenceScore: 72,
    severity: 68,
    reportCount: 7,
    residentialDensity: 80,
    estimatedPropertyAge: 18,
    description: "Half-dollar hail in Fort Myers and Cape Coral; multiple resident photos submitted.",
    county: "Lee",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-006",
    type: "hurricane",
    date: daysAgo(3),
    time: "09:00",
    city: "Naples",
    zipCode: "34102",
    windSpeedMph: 85,
    hailSizeInches: null,
    lat: 26.142,
    lng: -81.7948,
    source: "NHC Advisory Archive (sample)",
    confidence: "verified",
    confidenceScore: 98,
    severity: 88,
    reportCount: 22,
    residentialDensity: 75,
    estimatedPropertyAge: 20,
    description: "Tropical storm / hurricane-force gusts along Collier County coastline; roof and awning damage.",
    county: "Collier",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-007",
    type: "wind",
    date: daysAgo(4),
    time: "17:30",
    city: "Miami",
    zipCode: "33130",
    windSpeedMph: 62,
    hailSizeInches: null,
    lat: 25.7617,
    lng: -80.1918,
    source: "ASOS — KMIA (sample)",
    confidence: "verified",
    confidenceScore: 93,
    severity: 72,
    reportCount: 8,
    residentialDensity: 90,
    estimatedPropertyAge: 40,
    description: "Strong outflow winds across Brickell and Little Havana; power lines and shingles down.",
    county: "Miami-Dade",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-008",
    type: "severe_thunderstorm",
    date: daysAgo(5),
    time: "19:15",
    city: "Gainesville",
    zipCode: "32601",
    windSpeedMph: 55,
    hailSizeInches: 1.0,
    lat: 29.6516,
    lng: -82.3248,
    source: "NWS Storm Reports (sample)",
    confidence: "high",
    confidenceScore: 84,
    severity: 66,
    reportCount: 5,
    residentialDensity: 60,
    estimatedPropertyAge: 25,
    description: "Severe storms with quarter-sized hail west of Gainesville.",
    county: "Alachua",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-009",
    type: "hail",
    date: daysAgo(6),
    time: "12:40",
    city: "Pensacola",
    zipCode: "32501",
    windSpeedMph: 48,
    hailSizeInches: 2.0,
    lat: 30.4213,
    lng: -87.2169,
    source: "NWS Mobile/Pensacola (sample)",
    confidence: "high",
    confidenceScore: 87,
    severity: 86,
    reportCount: 12,
    residentialDensity: 68,
    estimatedPropertyAge: 32,
    description: "Egg-sized hail reported; vehicle and roof damage in midtown Pensacola.",
    county: "Escambia",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-010",
    type: "tornado",
    date: daysAgo(8),
    time: "20:05",
    city: "Ocala",
    zipCode: "34471",
    windSpeedMph: 110,
    hailSizeInches: null,
    lat: 29.1872,
    lng: -82.1401,
    source: "NWS Damage Survey (sample)",
    confidence: "verified",
    confidenceScore: 96,
    severity: 94,
    reportCount: 4,
    residentialDensity: 55,
    estimatedPropertyAge: 27,
    description: "EF2 tornado tracked through Marion County suburbs; significant roof loss.",
    county: "Marion",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-011",
    type: "wind",
    date: daysAgo(10),
    time: "11:20",
    city: "Sarasota",
    zipCode: "34236",
    windSpeedMph: 52,
    hailSizeInches: null,
    lat: 27.3364,
    lng: -82.5307,
    source: "Local news — weather blog (sample)",
    confidence: "medium",
    confidenceScore: 68,
    severity: 58,
    reportCount: 3,
    residentialDensity: 74,
    estimatedPropertyAge: 35,
    description: "Gusty squall line with isolated roof and fence damage near downtown Sarasota.",
    county: "Sarasota",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-012",
    type: "hurricane",
    date: daysAgo(14),
    time: "06:30",
    city: "Panama City",
    zipCode: "32401",
    windSpeedMph: 78,
    hailSizeInches: null,
    lat: 30.1588,
    lng: -85.6602,
    source: "NHC / NWS Tallahassee (sample)",
    confidence: "verified",
    confidenceScore: 97,
    severity: 80,
    reportCount: 18,
    residentialDensity: 62,
    estimatedPropertyAge: 24,
    description: "Tropical cyclone remnant winds; coastal Bay County reporting structural damage.",
    county: "Bay",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-013",
    type: "severe_thunderstorm",
    date: daysAgo(18),
    time: "16:45",
    city: "Tallahassee",
    zipCode: "32301",
    windSpeedMph: 60,
    hailSizeInches: 0.88,
    lat: 30.4383,
    lng: -84.2807,
    source: "NWS Tallahassee Alert (sample)",
    confidence: "high",
    confidenceScore: 83,
    severity: 64,
    reportCount: 6,
    residentialDensity: 66,
    estimatedPropertyAge: 29,
    description: "Severe thunderstorm warning verified with wind and penny-to-nickel hail.",
    county: "Leon",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-014",
    type: "hail",
    date: daysAgo(22),
    time: "15:00",
    city: "West Palm Beach",
    zipCode: "33401",
    windSpeedMph: 38,
    hailSizeInches: 1.5,
    lat: 26.7153,
    lng: -80.0534,
    source: "Public storm spotter network (sample)",
    confidence: "medium",
    confidenceScore: 70,
    severity: 74,
    reportCount: 9,
    residentialDensity: 85,
    estimatedPropertyAge: 26,
    description: "Ping-pong hail across West Palm Beach residential corridors.",
    county: "Palm Beach",
    createdAt: new Date().toISOString(),
  },
  {
    id: "storm-015",
    type: "wind",
    date: daysAgo(25),
    time: "21:10",
    city: "Daytona Beach",
    zipCode: "32114",
    windSpeedMph: 70,
    hailSizeInches: null,
    lat: 29.2108,
    lng: -81.0228,
    source: "ASOS — KDAB (sample)",
    confidence: "verified",
    confidenceScore: 92,
    severity: 76,
    reportCount: 7,
    residentialDensity: 71,
    estimatedPropertyAge: 33,
    description: "Thunderstorm microburst near Daytona International; roof panel losses reported.",
    county: "Volusia",
    createdAt: new Date().toISOString(),
  },
];
