import type {
  AppUser,
  HousekeepingTask,
  Notification,
  Profile,
  Property,
  Reservation,
  Room,
  StayFlowState,
} from "@/types";
import { addDays, toISODate, uid } from "@/lib/utils";

const TODAY = toISODate(new Date());

const OWNER_ID = "user_owner_demo";
const PROPERTY_HARBOR = "prop_harbor_view";
const PROPERTY_ALPINE = "prop_alpine_lodge";

function room(
  partial: Omit<Room, "created_at" | "updated_at"> & {
    created_at?: string;
    updated_at?: string;
  }
): Room {
  return {
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ...partial,
  };
}

function reservation(
  partial: Omit<Reservation, "created_at" | "updated_at" | "remaining_balance"> & {
    remaining_balance?: number;
  }
): Reservation {
  const remaining =
    partial.remaining_balance ??
    Math.max(0, partial.total_amount - partial.deposit_paid);
  return {
    remaining_balance: remaining,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    ...partial,
  };
}

export const DEMO_USERS: AppUser[] = [
  {
    id: OWNER_ID,
    email: "demo@stayflow.app",
    password: "demo1234",
    full_name: "Alex Rivera",
    role: "owner",
  },
  {
    id: "user_manager_demo",
    email: "manager@stayflow.app",
    password: "demo1234",
    full_name: "Jordan Lee",
    role: "manager",
  },
  {
    id: "user_front_demo",
    email: "front@stayflow.app",
    password: "demo1234",
    full_name: "Sam Chen",
    role: "receptionist",
  },
  {
    id: "user_hk_demo",
    email: "housekeeping@stayflow.app",
    password: "demo1234",
    full_name: "Taylor Brooks",
    role: "housekeeping",
  },
];

export const DEMO_PROFILE: Profile = {
  id: OWNER_ID,
  email: "demo@stayflow.app",
  full_name: "Alex Rivera",
  role: "owner",
  created_at: "2025-01-10T10:00:00.000Z",
};

export const DEMO_PROPERTIES: Property[] = [
  {
    id: PROPERTY_HARBOR,
    owner_id: OWNER_ID,
    name: "Harbor View Inn",
    address: "214 Pier Avenue",
    city: "Santa Monica",
    country: "United States",
    description:
      "Boutique waterfront hotel with ocean-view rooms, courtyard lounges, and concierge service for leisure travelers.",
    property_type: "hotel",
    created_at: "2025-02-01T12:00:00.000Z",
    updated_at: "2025-02-01T12:00:00.000Z",
  },
  {
    id: PROPERTY_ALPINE,
    owner_id: OWNER_ID,
    name: "Alpine Loft Collective",
    address: "88 Summit Trail",
    city: "Aspen",
    country: "United States",
    description:
      "Design-forward loft rentals for weekend ski trips and summer alpine escapes, managed as a multi-unit Airbnb portfolio.",
    property_type: "airbnb",
    created_at: "2025-03-12T12:00:00.000Z",
    updated_at: "2025-03-12T12:00:00.000Z",
  },
];

export const DEMO_ROOMS: Room[] = [
  room({
    id: "room_hv_101",
    property_id: PROPERTY_HARBOR,
    name: "Ocean King",
    room_number: "101",
    capacity: 2,
    price_per_night: 289,
    room_type: "King Suite",
    description: "Corner king with floor-to-ceiling ocean windows.",
    status: "occupied",
  }),
  room({
    id: "room_hv_102",
    property_id: PROPERTY_HARBOR,
    name: "Harbor Queen",
    room_number: "102",
    capacity: 2,
    price_per_night: 219,
    room_type: "Queen Deluxe",
    description: "Quiet courtyard queen with soaking tub.",
    status: "available",
  }),
  room({
    id: "room_hv_201",
    property_id: PROPERTY_HARBOR,
    name: "Pier Family",
    room_number: "201",
    capacity: 4,
    price_per_night: 349,
    room_type: "Family Suite",
    description: "Two-queen family suite with kitchenette.",
    status: "cleaning",
  }),
  room({
    id: "room_hv_202",
    property_id: PROPERTY_HARBOR,
    name: "Sunset Studio",
    room_number: "202",
    capacity: 2,
    price_per_night: 199,
    room_type: "Studio",
    description: "Compact studio overlooking the pier walk.",
    status: "available",
  }),
  room({
    id: "room_hv_301",
    property_id: PROPERTY_HARBOR,
    name: "Captain Penthouse",
    room_number: "301",
    capacity: 3,
    price_per_night: 499,
    room_type: "Penthouse",
    description: "Top-floor penthouse with private terrace.",
    status: "occupied",
  }),
  room({
    id: "room_al_1a",
    property_id: PROPERTY_ALPINE,
    name: "Cedar Loft",
    room_number: "1A",
    capacity: 4,
    price_per_night: 320,
    room_type: "Loft",
    description: "Timber loft with fireplace and mountain outlook.",
    status: "occupied",
  }),
  room({
    id: "room_al_1b",
    property_id: PROPERTY_ALPINE,
    name: "Snowpine Cabin",
    room_number: "1B",
    capacity: 2,
    price_per_night: 275,
    room_type: "Cabin",
    description: "One-bedroom cabin near the gondola shuttle.",
    status: "available",
  }),
  room({
    id: "room_al_2a",
    property_id: PROPERTY_ALPINE,
    name: "Summit Duplex",
    room_number: "2A",
    capacity: 6,
    price_per_night: 480,
    room_type: "Duplex",
    description: "Two-level duplex ideal for group stays.",
    status: "maintenance",
  }),
];

export const DEMO_RESERVATIONS: Reservation[] = [
  reservation({
    id: "res_001",
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_101",
    guest_first_name: "Maya",
    guest_last_name: "Patel",
    guest_email: "maya.patel@email.com",
    guest_phone: "+1 310-555-0142",
    check_in: addDays(TODAY, -2),
    check_out: addDays(TODAY, 2),
    number_of_guests: 2,
    total_amount: 1156,
    deposit_paid: 400,
    status: "checked_in",
    internal_notes: "VIP — complimentary late checkout if available.",
    guest_requests: "High floor, quiet room.",
  }),
  reservation({
    id: "res_002",
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_301",
    guest_first_name: "Daniel",
    guest_last_name: "Okoye",
    guest_email: "d.okoye@email.com",
    guest_phone: "+1 415-555-0198",
    check_in: addDays(TODAY, -1),
    check_out: addDays(TODAY, 3),
    number_of_guests: 2,
    total_amount: 1996,
    deposit_paid: 1996,
    status: "checked_in",
    internal_notes: "Paid in full.",
    guest_requests: "Celebration — anniversary cakes on arrival.",
  }),
  reservation({
    id: "res_003",
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_102",
    guest_first_name: "Elena",
    guest_last_name: "Rossi",
    guest_email: "elena.rossi@email.com",
    guest_phone: "+39 02 555 8821",
    check_in: TODAY,
    check_out: addDays(TODAY, 4),
    number_of_guests: 1,
    total_amount: 876,
    deposit_paid: 200,
    status: "confirmed",
    internal_notes: "Arriving after 8pm.",
    guest_requests: "Extra pillows.",
  }),
  reservation({
    id: "res_004",
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_202",
    guest_first_name: "Chris",
    guest_last_name: "Nguyen",
    guest_email: "chris.n@email.com",
    guest_phone: "+1 212-555-0177",
    check_in: TODAY,
    check_out: addDays(TODAY, 1),
    number_of_guests: 2,
    total_amount: 199,
    deposit_paid: 0,
    status: "pending",
    internal_notes: "Awaiting deposit confirmation.",
    guest_requests: "",
  }),
  reservation({
    id: "res_005",
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_201",
    guest_first_name: "Priya",
    guest_last_name: "Shah",
    guest_email: "priya.shah@email.com",
    guest_phone: "+1 323-555-0109",
    check_in: addDays(TODAY, -3),
    check_out: TODAY,
    number_of_guests: 3,
    total_amount: 1047,
    deposit_paid: 500,
    status: "checked_out",
    internal_notes: "Departure this morning.",
    guest_requests: "Early breakfast.",
  }),
  reservation({
    id: "res_006",
    property_id: PROPERTY_ALPINE,
    room_id: "room_al_1a",
    guest_first_name: "Noah",
    guest_last_name: "Berg",
    guest_email: "noah.berg@email.com",
    guest_phone: "+1 970-555-0133",
    check_in: addDays(TODAY, -1),
    check_out: addDays(TODAY, 5),
    number_of_guests: 4,
    total_amount: 1920,
    deposit_paid: 600,
    status: "checked_in",
    internal_notes: "",
    guest_requests: "Ski storage access.",
  }),
  reservation({
    id: "res_007",
    property_id: PROPERTY_ALPINE,
    room_id: "room_al_1b",
    guest_first_name: "Sofia",
    guest_last_name: "Martinez",
    guest_email: "sofia.m@email.com",
    guest_phone: "+1 720-555-0164",
    check_in: addDays(TODAY, 2),
    check_out: addDays(TODAY, 6),
    number_of_guests: 2,
    total_amount: 1100,
    deposit_paid: 275,
    status: "confirmed",
    internal_notes: "",
    guest_requests: "Pet-friendly bedding.",
  }),
  reservation({
    id: "res_008",
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_102",
    guest_first_name: "James",
    guest_last_name: "Whitaker",
    guest_email: "j.whitaker@email.com",
    guest_phone: "+1 617-555-0180",
    check_in: addDays(TODAY, 5),
    check_out: addDays(TODAY, 8),
    number_of_guests: 2,
    total_amount: 657,
    deposit_paid: 219,
    status: "confirmed",
    internal_notes: "",
    guest_requests: "",
  }),
  reservation({
    id: "res_009",
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_101",
    guest_first_name: "Ava",
    guest_last_name: "Kim",
    guest_email: "ava.kim@email.com",
    guest_phone: "+1 206-555-0121",
    check_in: addDays(TODAY, 3),
    check_out: addDays(TODAY, 7),
    number_of_guests: 2,
    total_amount: 1156,
    deposit_paid: 0,
    status: "pending",
    internal_notes: "Corporate rate pending approval.",
    guest_requests: "Desk workspace.",
  }),
  reservation({
    id: "res_010",
    property_id: PROPERTY_ALPINE,
    room_id: "room_al_2a",
    guest_first_name: "Liam",
    guest_last_name: "Foster",
    guest_email: "liam.foster@email.com",
    guest_phone: "+1 303-555-0190",
    check_in: addDays(TODAY, -10),
    check_out: addDays(TODAY, -7),
    number_of_guests: 5,
    total_amount: 1440,
    deposit_paid: 1440,
    status: "cancelled",
    internal_notes: "Guest cancelled — full refund issued.",
    guest_requests: "",
  }),
];

export const DEMO_TASKS: HousekeepingTask[] = [
  {
    id: uid("task"),
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_201",
    task_type: "clean_room",
    status: "in_progress",
    notes: "Checkout turnover — deep clean bathtub.",
    assigned_to: "user_hk_demo",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: uid("task"),
    property_id: PROPERTY_HARBOR,
    room_id: "room_hv_102",
    task_type: "inspect_room",
    status: "pending",
    notes: "Pre-arrival inspection for Elena Rossi.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: uid("task"),
    property_id: PROPERTY_ALPINE,
    room_id: "room_al_2a",
    task_type: "maintenance_request",
    status: "in_progress",
    notes: "HVAC diagnostic — unit offline.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
  {
    id: "notif_1",
    user_id: OWNER_ID,
    title: "Check-ins today",
    message: "Elena Rossi and Chris Nguyen arrive at Harbor View Inn today.",
    type: "check_in",
    read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "notif_2",
    user_id: OWNER_ID,
    title: "Checkout due",
    message: "Priya Shah is departing room 201 this morning.",
    type: "check_out",
    read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "notif_3",
    user_id: OWNER_ID,
    title: "Unpaid balance",
    message: "Chris Nguyen has $199 remaining on a pending reservation.",
    type: "unpaid",
    read: false,
    created_at: new Date().toISOString(),
  },
  {
    id: "notif_4",
    user_id: OWNER_ID,
    title: "New reservation",
    message: "Sofia Martinez booked Snowpine Cabin for 4 nights.",
    type: "new_reservation",
    read: true,
    created_at: addDays(TODAY, -1) + "T14:00:00.000Z",
  },
  {
    id: "notif_5",
    user_id: OWNER_ID,
    title: "Maintenance request",
    message: "Summit Duplex HVAC needs attention.",
    type: "maintenance",
    read: false,
    created_at: new Date().toISOString(),
  },
];

export function createSeedState(): StayFlowState {
  return {
    user: null,
    users: DEMO_USERS,
    properties: DEMO_PROPERTIES,
    rooms: DEMO_ROOMS,
    reservations: DEMO_RESERVATIONS,
    housekeeping_tasks: DEMO_TASKS,
    notifications: DEMO_NOTIFICATIONS,
  };
}
