import type { Card } from '../types/game'

export const CARDS: Card[] = [
  // Products
  {
    id: 'protein-powder',
    name: 'Protein Powder',
    description: 'Quick nutrition for busy lifestyles',
    slotType: 'product',
    tags: ['health', 'fitness', 'convenience', 'supplement'],
    strength: 75,
    affinities: { professionals: 20, fitness: 25, convenience: 15 },
    unlockLevel: 1,
    emoji: '💪',
  },
  {
    id: 'fishing-rod',
    name: 'Fishing Rod',
    description: 'Premium outdoor fishing gear',
    slotType: 'product',
    tags: ['outdoor', 'hobby', 'leisure', 'sport'],
    strength: 60,
    affinities: { outdoor: 25, hobby: 20, retirees: 15 },
    unlockLevel: 1,
    emoji: '🎣',
  },
  {
    id: 'sleep-mask',
    name: 'Sleep Mask',
    description: 'Blocks light for deeper rest',
    slotType: 'product',
    tags: ['wellness', 'sleep', 'health', 'accessory'],
    strength: 70,
    affinities: { students: 15, wellness: 25, sleep: 30 },
    unlockLevel: 1,
    emoji: '😴',
  },
  {
    id: 'online-course',
    name: 'Online Course',
    description: 'Self-paced skill development',
    slotType: 'product',
    tags: ['education', 'digital', 'career', 'skill'],
    strength: 72,
    affinities: { students: 20, professionals: 25, career: 20 },
    unlockLevel: 2,
    emoji: '📚',
  },
  {
    id: 'skincare-set',
    name: 'Skincare Set',
    description: 'Complete daily skincare routine',
    slotType: 'product',
    tags: ['beauty', 'self-care', 'premium', 'routine'],
    strength: 78,
    affinities: { beauty: 25, millennials: 20, 'self-care': 20 },
    unlockLevel: 2,
    emoji: '✨',
  },
  {
    id: 'meal-kit',
    name: 'Meal Kit',
    description: 'Pre-portioned ingredients delivered',
    slotType: 'product',
    tags: ['food', 'convenience', 'health', 'subscription'],
    strength: 74,
    affinities: { parents: 25, convenience: 20, health: 15 },
    unlockLevel: 3,
    emoji: '🥗',
  },
  {
    id: 'wireless-earbuds',
    name: 'Wireless Earbuds',
    description: 'Premium audio on the go',
    slotType: 'product',
    tags: ['tech', 'gadget', 'lifestyle', 'portable'],
    strength: 80,
    affinities: { commuters: 20, tech: 25, students: 15 },
    unlockLevel: 3,
    emoji: '🎧',
  },
  {
    id: 'pet-toy-bundle',
    name: 'Pet Toy Bundle',
    description: 'Interactive toys for dogs and cats',
    slotType: 'product',
    tags: ['pets', 'lifestyle', 'gift', 'subscription'],
    strength: 68,
    affinities: { 'pet-owners': 30, gift: 15 },
    unlockLevel: 4,
    emoji: '🐾',
  },

  // Markets
  {
    id: 'busy-professionals',
    name: 'Busy Professionals',
    description: 'Time-starved office workers',
    slotType: 'market',
    tags: ['professionals', 'convenience', 'premium', 'commuters'],
    strength: 75,
    affinities: { convenience: 20, health: 15, career: 15 },
    unlockLevel: 1,
    emoji: '💼',
  },
  {
    id: 'college-students',
    name: 'College Students',
    description: 'Budget-conscious young adults',
    slotType: 'market',
    tags: ['students', 'budget', 'digital-native', 'social'],
    strength: 65,
    affinities: { budget: 20, digital: 15, social: 15 },
    unlockLevel: 1,
    emoji: '🎓',
  },
  {
    id: 'new-parents',
    name: 'New Parents',
    description: 'Sleep-deprived caregivers',
    slotType: 'market',
    tags: ['parents', 'family', 'convenience', 'safety'],
    strength: 72,
    affinities: { convenience: 25, family: 20, safety: 15 },
    unlockLevel: 2,
    emoji: '👶',
  },
  {
    id: 'fitness-enthusiasts',
    name: 'Fitness Enthusiasts',
    description: 'Gym-goers and athletes',
    slotType: 'market',
    tags: ['fitness', 'health', 'performance', 'active'],
    strength: 78,
    affinities: { fitness: 25, health: 20, performance: 15 },
    unlockLevel: 2,
    emoji: '🏋️',
  },
  {
    id: 'outdoor-adventurers',
    name: 'Outdoor Adventurers',
    description: 'Hikers, campers, and anglers',
    slotType: 'market',
    tags: ['outdoor', 'hobby', 'adventure', 'sport'],
    strength: 70,
    affinities: { outdoor: 25, hobby: 20, adventure: 15 },
    unlockLevel: 3,
    emoji: '🏕️',
  },
  {
    id: 'beauty-influencers',
    name: 'Beauty Enthusiasts',
    description: 'Skincare and makeup lovers',
    slotType: 'market',
    tags: ['beauty', 'self-care', 'social', 'premium'],
    strength: 76,
    affinities: { beauty: 25, 'self-care': 20, social: 15 },
    unlockLevel: 3,
    emoji: '💄',
  },
  {
    id: 'remote-workers',
    name: 'Remote Workers',
    description: 'Work-from-home professionals',
    slotType: 'market',
    tags: ['professionals', 'tech', 'convenience', 'home'],
    strength: 74,
    affinities: { tech: 20, convenience: 15, productivity: 20 },
    unlockLevel: 4,
    emoji: '🏠',
  },
  {
    id: 'pet-owners',
    name: 'Pet Owners',
    description: 'Devoted dog and cat parents',
    slotType: 'market',
    tags: ['pet-owners', 'lifestyle', 'family', 'gift'],
    strength: 71,
    affinities: { pets: 25, lifestyle: 15, gift: 10 },
    unlockLevel: 4,
    emoji: '🐕',
  },

  // Problems
  {
    id: 'no-time-cook',
    name: 'No Time To Cook',
    description: 'Healthy eating feels impossible',
    slotType: 'problem',
    tags: ['convenience', 'health', 'time', 'nutrition'],
    strength: 80,
    affinities: { convenience: 25, health: 20, professionals: 15 },
    unlockLevel: 2,
    emoji: '⏰',
  },
  {
    id: 'bad-sleep',
    name: 'Bad Sleep',
    description: 'Trouble falling and staying asleep',
    slotType: 'problem',
    tags: ['sleep', 'wellness', 'stress', 'health'],
    strength: 78,
    affinities: { sleep: 30, wellness: 20, stress: 15 },
    unlockLevel: 2,
    emoji: '🌙',
  },
  {
    id: 'career-stagnation',
    name: 'Career Stagnation',
    description: 'Skills not keeping up with industry',
    slotType: 'problem',
    tags: ['career', 'education', 'skill', 'growth'],
    strength: 75,
    affinities: { career: 25, education: 20, skill: 15 },
    unlockLevel: 2,
    emoji: '📈',
  },
  {
    id: 'skin-concerns',
    name: 'Skin Concerns',
    description: 'Acne, dryness, or uneven tone',
    slotType: 'problem',
    tags: ['beauty', 'self-care', 'confidence', 'routine'],
    strength: 76,
    affinities: { beauty: 25, 'self-care': 20, confidence: 15 },
    unlockLevel: 3,
    emoji: '🪞',
  },
  {
    id: 'bored-pets',
    name: 'Bored Pets',
    description: 'Destructive behavior from lack of stimulation',
    slotType: 'problem',
    tags: ['pets', 'lifestyle', 'behavior', 'care'],
    strength: 72,
    affinities: { pets: 25, lifestyle: 15, care: 15 },
    unlockLevel: 3,
    emoji: '🐱',
  },
  {
    id: 'no-hobbies',
    name: 'No Outdoor Hobbies',
    description: 'Stuck indoors, craving adventure',
    slotType: 'problem',
    tags: ['outdoor', 'hobby', 'leisure', 'wellness'],
    strength: 70,
    affinities: { outdoor: 25, hobby: 20, leisure: 15 },
    unlockLevel: 3,
    emoji: '🌲',
  },
  {
    id: 'gym-plateau',
    name: 'Gym Plateau',
    description: 'Fitness gains have stalled',
    slotType: 'problem',
    tags: ['fitness', 'performance', 'nutrition', 'health'],
    strength: 77,
    affinities: { fitness: 25, performance: 20, nutrition: 15 },
    unlockLevel: 4,
    emoji: '🏃',
  },
  {
    id: 'poor-focus',
    name: 'Poor Focus',
    description: 'Distractions ruin productivity',
    slotType: 'problem',
    tags: ['productivity', 'tech', 'convenience', 'stress'],
    strength: 74,
    affinities: { productivity: 25, tech: 15, stress: 15 },
    unlockLevel: 4,
    emoji: '🧠',
  },

  // Hooks
  {
    id: 'healthy-60-seconds',
    name: 'Healthy Meals In 60 Seconds',
    description: 'Speed meets nutrition',
    slotType: 'hook',
    tags: ['health', 'convenience', 'nutrition', 'speed'],
    strength: 82,
    affinities: { convenience: 25, health: 20, nutrition: 20 },
    unlockLevel: 3,
    emoji: '⚡',
  },
  {
    id: 'better-grades',
    name: 'Get Better Grades',
    description: 'Study smarter, not harder',
    slotType: 'hook',
    tags: ['education', 'students', 'performance', 'skill'],
    strength: 55,
    affinities: { education: 20, students: 20, skill: 15 },
    unlockLevel: 3,
    emoji: '📝',
  },
  {
    id: 'sleep-like-baby',
    name: 'Sleep Like A Baby Tonight',
    description: 'Wake up refreshed every morning',
    slotType: 'hook',
    tags: ['sleep', 'wellness', 'rest', 'health'],
    strength: 80,
    affinities: { sleep: 30, wellness: 20, rest: 15 },
    unlockLevel: 3,
    emoji: '🌟',
  },
  {
    id: 'glow-up',
    name: 'Your Glow-Up Starts Here',
    description: 'Transform your skin in 14 days',
    slotType: 'hook',
    tags: ['beauty', 'self-care', 'transformation', 'confidence'],
    strength: 79,
    affinities: { beauty: 25, 'self-care': 20, transformation: 15 },
    unlockLevel: 4,
    emoji: '✨',
  },
  {
    id: 'level-up-career',
    name: 'Level Up Your Career',
    description: 'Skills employers actually want',
    slotType: 'hook',
    tags: ['career', 'education', 'growth', 'skill'],
    strength: 78,
    affinities: { career: 25, education: 20, growth: 15 },
    unlockLevel: 4,
    emoji: '🚀',
  },
  {
    id: 'catch-more-fish',
    name: 'Catch More Fish This Weekend',
    description: 'Pro anglers swear by this gear',
    slotType: 'hook',
    tags: ['outdoor', 'hobby', 'sport', 'adventure'],
    strength: 76,
    affinities: { outdoor: 25, hobby: 20, sport: 15 },
    unlockLevel: 4,
    emoji: '🐟',
  },
  {
    id: 'happy-pet-guarantee',
    name: 'Happy Pet Guarantee',
    description: 'Toys pets actually play with',
    slotType: 'hook',
    tags: ['pets', 'lifestyle', 'guarantee', 'care'],
    strength: 75,
    affinities: { pets: 25, lifestyle: 15, care: 15 },
    unlockLevel: 5,
    emoji: '🎾',
  },
  {
    id: 'deep-focus-mode',
    name: 'Enter Deep Focus Mode',
    description: 'Block the noise, find your flow',
    slotType: 'hook',
    tags: ['productivity', 'tech', 'focus', 'performance'],
    strength: 77,
    affinities: { productivity: 25, tech: 20, focus: 15 },
    unlockLevel: 5,
    emoji: '🎯',
  },

  // Offers
  {
    id: 'buy-2-get-1',
    name: 'Buy 2 Get 1 Free',
    description: 'Volume incentive for repeat buyers',
    slotType: 'offer',
    tags: ['bundle', 'value', 'subscription', 'volume'],
    strength: 78,
    affinities: { supplement: 20, consumable: 20, value: 15 },
    unlockLevel: 4,
    emoji: '🎁',
  },
  {
    id: 'free-trial',
    name: '7-Day Free Trial',
    description: 'Try before you commit',
    slotType: 'offer',
    tags: ['digital', 'trial', 'low-risk', 'subscription'],
    strength: 72,
    affinities: { digital: 25, subscription: 20, education: 15 },
    unlockLevel: 4,
    emoji: '🆓',
  },
  {
    id: 'flash-sale-50',
    name: '50% Flash Sale',
    description: 'Urgency-driven deep discount',
    slotType: 'offer',
    tags: ['urgency', 'discount', 'impulse', 'value'],
    strength: 70,
    affinities: { impulse: 20, value: 20, budget: 15 },
    unlockLevel: 4,
    emoji: '🔥',
  },
  {
    id: 'free-shipping',
    name: 'Free Shipping Over $50',
    description: 'Removes purchase friction',
    slotType: 'offer',
    tags: ['shipping', 'value', 'premium', 'convenience'],
    strength: 74,
    affinities: { premium: 15, convenience: 20, value: 15 },
    unlockLevel: 5,
    emoji: '📦',
  },
  {
    id: 'money-back',
    name: '30-Day Money Back',
    description: 'Risk reversal builds trust',
    slotType: 'offer',
    tags: ['guarantee', 'trust', 'premium', 'low-risk'],
    strength: 76,
    affinities: { trust: 25, premium: 15, guarantee: 20 },
    unlockLevel: 5,
    emoji: '✅',
  },
  {
    id: 'subscribe-save',
    name: 'Subscribe & Save 20%',
    description: 'Recurring revenue model',
    slotType: 'offer',
    tags: ['subscription', 'recurring', 'value', 'loyalty'],
    strength: 80,
    affinities: { subscription: 25, recurring: 20, loyalty: 15 },
    unlockLevel: 5,
    emoji: '🔄',
  },
  {
    id: 'limited-edition',
    name: 'Limited Edition Drop',
    description: 'Scarcity creates demand',
    slotType: 'offer',
    tags: ['scarcity', 'premium', 'urgency', 'exclusive'],
    strength: 73,
    affinities: { premium: 20, scarcity: 25, exclusive: 15 },
    unlockLevel: 6,
    emoji: '💎',
  },
  {
    id: 'bundle-deal',
    name: 'Starter Bundle — Save 35%',
    description: 'Complete package at a discount',
    slotType: 'offer',
    tags: ['bundle', 'value', 'starter', 'comprehensive'],
    strength: 77,
    affinities: { bundle: 25, starter: 20, comprehensive: 15 },
    unlockLevel: 6,
    emoji: '📦',
  },

  // Ads
  {
    id: 'tiktok-ugc',
    name: 'TikTok UGC Video',
    description: 'Authentic creator content',
    slotType: 'ad',
    tags: ['social', 'video', 'young', 'viral'],
    strength: 82,
    affinities: { students: 20, social: 25, viral: 20 },
    unlockLevel: 5,
    emoji: '📱',
  },
  {
    id: 'google-search',
    name: 'Google Search Ads',
    description: 'Capture high-intent buyers',
    slotType: 'ad',
    tags: ['search', 'intent', 'professional', 'targeted'],
    strength: 78,
    affinities: { professionals: 20, intent: 25, targeted: 15 },
    unlockLevel: 5,
    emoji: '🔍',
  },
  {
    id: 'instagram-influencer',
    name: 'Instagram Influencer',
    description: 'Visual lifestyle marketing',
    slotType: 'ad',
    tags: ['social', 'visual', 'beauty', 'lifestyle'],
    strength: 80,
    affinities: { beauty: 25, lifestyle: 20, visual: 15 },
    unlockLevel: 5,
    emoji: '📸',
  },
  {
    id: 'facebook-retargeting',
    name: 'Facebook Retargeting',
    description: 'Re-engage warm visitors',
    slotType: 'ad',
    tags: ['retargeting', 'conversion', 'data', 'mature'],
    strength: 76,
    affinities: { retargeting: 25, conversion: 20, data: 15 },
    unlockLevel: 5,
    emoji: '🎯',
  },
  {
    id: 'youtube-review',
    name: 'YouTube Product Review',
    description: 'In-depth trust building',
    slotType: 'ad',
    tags: ['video', 'trust', 'education', 'detailed'],
    strength: 77,
    affinities: { education: 20, trust: 25, detailed: 15 },
    unlockLevel: 6,
    emoji: '▶️',
  },
  {
    id: 'podcast-sponsor',
    name: 'Podcast Sponsorship',
    description: 'Niche audience targeting',
    slotType: 'ad',
    tags: ['audio', 'niche', 'trust', 'professional'],
    strength: 74,
    affinities: { niche: 25, trust: 20, professional: 15 },
    unlockLevel: 6,
    emoji: '🎙️',
  },
  {
    id: 'linkedin-ads',
    name: 'LinkedIn Ads',
    description: 'B2B and career-focused reach',
    slotType: 'ad',
    tags: ['professional', 'b2b', 'career', 'targeted'],
    strength: 75,
    affinities: { career: 25, professional: 20, b2b: 15 },
    unlockLevel: 6,
    emoji: '💼',
  },
  {
    id: 'email-campaign',
    name: 'Email Campaign',
    description: 'Owned audience, high ROI',
    slotType: 'ad',
    tags: ['email', 'owned', 'loyalty', 'retention'],
    strength: 79,
    affinities: { loyalty: 25, retention: 20, owned: 15 },
    unlockLevel: 6,
    emoji: '📧',
  },

  // Landing Pages
  {
    id: 'simple-store',
    name: 'Simple One-Product Store',
    description: 'Single focus, minimal friction',
    slotType: 'landing',
    tags: ['simple', 'focused', 'conversion', 'direct'],
    strength: 80,
    affinities: { simple: 25, focused: 20, conversion: 15 },
    unlockLevel: 6,
    emoji: '🛒',
  },
  {
    id: 'long-form-sales',
    name: 'Long-Form Sales Page',
    description: 'Story-driven persuasion',
    slotType: 'landing',
    tags: ['story', 'detailed', 'education', 'trust'],
    strength: 76,
    affinities: { education: 20, trust: 25, detailed: 15 },
    unlockLevel: 6,
    emoji: '📄',
  },
  {
    id: 'quiz-funnel',
    name: 'Quiz Funnel',
    description: 'Personalized product recommendations',
    slotType: 'landing',
    tags: ['interactive', 'personalized', 'engagement', 'data'],
    strength: 78,
    affinities: { personalized: 25, interactive: 20, engagement: 15 },
    unlockLevel: 6,
    emoji: '❓',
  },
  {
    id: 'comparison-page',
    name: 'Comparison Landing Page',
    description: 'Position against competitors',
    slotType: 'landing',
    tags: ['comparison', 'competitive', 'rational', 'trust'],
    strength: 74,
    affinities: { competitive: 25, rational: 20, trust: 15 },
    unlockLevel: 6,
    emoji: '⚖️',
  },
  {
    id: 'video-landing',
    name: 'Video-First Landing Page',
    description: 'Hero video drives emotion',
    slotType: 'landing',
    tags: ['video', 'emotional', 'visual', 'engagement'],
    strength: 77,
    affinities: { video: 25, emotional: 20, visual: 15 },
    unlockLevel: 6,
    emoji: '🎬',
  },
  {
    id: 'subscription-portal',
    name: 'Subscription Portal',
    description: 'Recurring purchase optimized',
    slotType: 'landing',
    tags: ['subscription', 'recurring', 'loyalty', 'retention'],
    strength: 79,
    affinities: { subscription: 25, recurring: 20, loyalty: 15 },
    unlockLevel: 6,
    emoji: '🔁',
  },
]

export function getCardById(id: string): Card | undefined {
  return CARDS.find((c) => c.id === id)
}

export function getCardsForSlot(slotType: string, maxLevel: number, unlockedIds: string[]): Card[] {
  return CARDS.filter(
    (c) =>
      c.slotType === slotType &&
      c.unlockLevel <= maxLevel &&
      (c.unlockLevel <= 2 || unlockedIds.includes(c.id) || c.unlockLevel <= maxLevel),
  )
}

export function getAvailableCards(playerLevel: number, unlockedIds: string[]): Card[] {
  const starterIds = CARDS.filter((c) => c.unlockLevel <= 2).map((c) => c.id)
  const allUnlocked = new Set([...starterIds, ...unlockedIds])
  return CARDS.filter((c) => c.unlockLevel <= playerLevel && allUnlocked.has(c.id))
}

export const STARTER_CARD_IDS = CARDS.filter((c) => c.unlockLevel <= 2).map((c) => c.id)
