import type { TileConfig, TileId } from '../types/game'

const crossRecipes = [
  { pair: ['visionary', 'catalyst'] as [TileId, TileId], result: 'inspirational_leader' as TileId },
  { pair: ['catalyst', 'master'] as [TileId, TileId], result: 'industry_icon' as TileId },
  { pair: ['visionary', 'master'] as [TileId, TileId], result: 'thought_leader' as TileId },
]

export const TILES: Record<TileId, TileConfig> = {
  sharpness: {
    id: 'sharpness',
    name: 'Mic Recruit',
    logo: 'MR',
    icon: '🎤',
    category: 'sharpness',
    tier: 1,
    color: '#3b82f6',
    bgClass: 'from-slate-700 to-blue-900',
    borderClass: 'border-blue-400/60',
    description: 'A fresh speaker learning to command attention.',
    principle: 'Every legend starts with a single clear sentence.',
    challenge: 'Deliver one clear opening line.',
    pointsValue: 10,
    mergeResult: 'analyst',
    animationType: 'standard',
  },
  analyst: {
    id: 'analyst',
    name: 'Voice Analyst',
    logo: 'VA',
    icon: '🔍',
    category: 'sharpness',
    tier: 2,
    color: '#1d4ed8',
    bgClass: 'from-slate-800 to-blue-950',
    borderClass: 'border-blue-500/70',
    description: 'Breaks ideas into parts the crowd can follow.',
    principle: 'Clarity wins stages before charisma does.',
    challenge: 'Explain one idea in under ten words.',
    pointsValue: 25,
    mergeResult: 'strategist',
    animationType: 'standard',
  },
  strategist: {
    id: 'strategist',
    name: 'Stage Strategist',
    logo: 'ST',
    icon: '♟️',
    category: 'sharpness',
    tier: 3,
    color: '#4f46e5',
    bgClass: 'from-indigo-900 to-slate-900',
    borderClass: 'border-indigo-400/70',
    description: 'Plans every beat before stepping into the spotlight.',
    principle: 'Great speeches are designed, not improvised.',
    challenge: 'State your goal in one powerful sentence.',
    pointsValue: 50,
    mergeResult: 'visionary',
    animationType: 'standard',
  },
  visionary: {
    id: 'visionary',
    name: 'Vision Speaker',
    logo: 'VS',
    icon: '🔮',
    category: 'sharpness',
    tier: 4,
    color: '#7c3aed',
    bgClass: 'from-purple-900 to-indigo-950',
    borderClass: 'border-purple-400/80',
    description: 'Sees futures the audience has not imagined yet.',
    principle: 'Paint tomorrow and people will follow you there.',
    challenge: 'Describe a better future in one sentence.',
    pointsValue: 100,
    crossMergeRecipes: crossRecipes,
    animationType: 'standard',
  },
  enthusiasm: {
    id: 'enthusiasm',
    name: 'Spark Speaker',
    logo: 'SP',
    icon: '🔥',
    category: 'enthusiasm',
    tier: 1,
    color: '#f97316',
    bgClass: 'from-orange-800 to-red-950',
    borderClass: 'border-orange-400/60',
    description: 'Brings visible energy to every word spoken.',
    principle: 'Energy is contagious — the crowd feels your belief.',
    challenge: 'Say what excites you about your mission.',
    pointsValue: 10,
    mergeResult: 'motivator',
    animationType: 'standard',
  },
  motivator: {
    id: 'motivator',
    name: 'Rally Caller',
    logo: 'RC',
    icon: '📣',
    category: 'enthusiasm',
    tier: 2,
    color: '#ea580c',
    bgClass: 'from-orange-900 to-amber-950',
    borderClass: 'border-orange-500/70',
    description: 'Lifts the crowd when doubt creeps in.',
    principle: 'Encouragement turns hesitation into momentum.',
    challenge: 'Rally someone with one bold sentence.',
    pointsValue: 25,
    mergeResult: 'influencer',
    animationType: 'standard',
  },
  influencer: {
    id: 'influencer',
    name: 'Crowd Mover',
    logo: 'CM',
    icon: '🌟',
    category: 'enthusiasm',
    tier: 3,
    color: '#dc2626',
    bgClass: 'from-red-900 to-orange-950',
    borderClass: 'border-red-400/70',
    description: 'Shifts how people feel with every phrase.',
    principle: 'Influence is the art of shifting perspective.',
    challenge: 'Make a boring idea sound thrilling.',
    pointsValue: 50,
    mergeResult: 'catalyst',
    animationType: 'standard',
  },
  catalyst: {
    id: 'catalyst',
    name: 'Pulse Catalyst',
    logo: 'PC',
    icon: '⚡',
    category: 'enthusiasm',
    tier: 4,
    color: '#eab308',
    bgClass: 'from-amber-700 to-yellow-900',
    borderClass: 'border-yellow-400/80',
    description: 'Sparks action the moment they stop talking.',
    principle: 'The best speakers compel movement, not just applause.',
    challenge: 'Convince someone to act in one sentence.',
    pointsValue: 100,
    crossMergeRecipes: crossRecipes,
    animationType: 'cross-glow',
  },
  authority: {
    id: 'authority',
    name: 'Podium Guard',
    logo: 'PG',
    icon: '👑',
    category: 'authority',
    tier: 1,
    color: '#22c55e',
    bgClass: 'from-emerald-800 to-green-950',
    borderClass: 'border-green-400/60',
    description: 'Speaks with certainty from the first step on stage.',
    principle: 'Confidence comes from knowing your direction.',
    challenge: 'Give one clear instruction.',
    pointsValue: 10,
    mergeResult: 'professional',
    animationType: 'standard',
  },
  professional: {
    id: 'professional',
    name: 'Pro Presenter',
    logo: 'PP',
    icon: '💼',
    category: 'authority',
    tier: 2,
    color: '#15803d',
    bgClass: 'from-green-900 to-emerald-950',
    borderClass: 'border-green-500/70',
    description: 'Delivers with consistency under pressure.',
    principle: 'Reliability builds trust over time.',
    challenge: 'Explain how you would solve a common problem.',
    pointsValue: 25,
    mergeResult: 'expert',
    animationType: 'standard',
  },
  expert: {
    id: 'expert',
    name: 'Keynote Expert',
    logo: 'KE',
    icon: '🎓',
    category: 'authority',
    tier: 3,
    color: '#10b981',
    bgClass: 'from-teal-900 to-emerald-950',
    borderClass: 'border-emerald-400/70',
    description: 'Demonstrates mastery the audience can trust.',
    principle: 'Expertise earns the right to be heard.',
    challenge: 'Teach one principle in a single sentence.',
    pointsValue: 50,
    mergeResult: 'master',
    animationType: 'standard',
  },
  master: {
    id: 'master',
    name: 'Stage Master',
    logo: 'SM',
    icon: '🏆',
    category: 'authority',
    tier: 4,
    color: '#ca8a04',
    bgClass: 'from-amber-800 to-yellow-950',
    borderClass: 'border-amber-400/80',
    description: 'Leads through proven ability and presence.',
    principle: 'Mastery is demonstrated, not declared.',
    challenge: 'Make a strong recommendation and defend it.',
    pointsValue: 100,
    crossMergeRecipes: crossRecipes,
    animationType: 'spotlight',
  },
  inspirational_leader: {
    id: 'inspirational_leader',
    name: 'Spotlight Commander',
    logo: 'SC',
    icon: '✨',
    category: 'cross',
    tier: 5,
    color: '#a855f7',
    bgClass: 'from-purple-800 via-amber-800 to-yellow-900',
    borderClass: 'border-amber-400/90',
    description: 'Fuses vision with energy to own the stage.',
    principle: 'Vision without energy stays invisible.',
    challenge: 'Inspire belief in one unforgettable line.',
    pointsValue: 250,
    animationType: 'cross-glow',
  },
  industry_icon: {
    id: 'industry_icon',
    name: 'Hall Icon',
    logo: 'HI',
    icon: '⭐',
    category: 'cross',
    tier: 5,
    color: '#ef4444',
    bgClass: 'from-red-900 via-emerald-900 to-amber-900',
    borderClass: 'border-amber-300/90',
    description: 'A speaker the entire industry recognizes.',
    principle: 'Icons are built where impact meets integrity.',
    challenge: 'Define what makes a speaker truly credible.',
    pointsValue: 250,
    animationType: 'spotlight',
  },
  thought_leader: {
    id: 'thought_leader',
    name: 'Ideas Champion',
    logo: 'IC',
    icon: '💡',
    category: 'cross',
    tier: 5,
    color: '#6366f1',
    bgClass: 'from-indigo-900 via-emerald-900 to-amber-900',
    borderClass: 'border-indigo-300/90',
    description: 'Original thinking backed by earned trust.',
    principle: 'Ideas gain power when backed by experience.',
    challenge: 'Share one original insight from experience.',
    pointsValue: 250,
    animationType: 'idea-particles',
  },
  legendary_communicator: {
    id: 'legendary_communicator',
    name: 'Legend Orator',
    logo: 'LO',
    icon: '👑',
    category: 'legendary',
    tier: 6,
    color: '#fbbf24',
    bgClass: 'from-amber-500 via-yellow-500 to-amber-600',
    borderClass: 'border-yellow-200',
    description: 'The ultimate speaker — clarity, power, and proof united.',
    principle: 'Legendary speakers make people think, feel, and act.',
    challenge: 'Deliver one message that changes the room forever.',
    pointsValue: 1000,
    animationType: 'legendary',
  },
}

export const BASIC_TILE_IDS: TileId[] = ['sharpness', 'enthusiasm', 'authority']

export const ALL_TILE_IDS = Object.keys(TILES) as TileId[]

export const COLLECTION_SECTIONS = [
  { id: 'sharpness', title: 'Clarity Corps', tiles: ['sharpness', 'analyst', 'strategist', 'visionary'] as TileId[] },
  { id: 'enthusiasm', title: 'Energy Squad', tiles: ['enthusiasm', 'motivator', 'influencer', 'catalyst'] as TileId[] },
  { id: 'authority', title: 'Authority Guard', tiles: ['authority', 'professional', 'expert', 'master'] as TileId[] },
  {
    id: 'cross',
    title: 'Elite Fusion Speakers',
    tiles: ['inspirational_leader', 'industry_icon', 'thought_leader'] as TileId[],
  },
  { id: 'legendary', title: 'Legendary Unit', tiles: ['legendary_communicator'] as TileId[] },
]

export function getTile(id: TileId): TileConfig {
  return TILES[id]
}
