import type { TileConfig, TileId } from '../types/game'

const crossRecipes = [
  { pair: ['visionary', 'catalyst'] as [TileId, TileId], result: 'inspirational_leader' as TileId },
  { pair: ['catalyst', 'master'] as [TileId, TileId], result: 'industry_icon' as TileId },
  { pair: ['visionary', 'master'] as [TileId, TileId], result: 'thought_leader' as TileId },
]

export const TILES: Record<TileId, TileConfig> = {
  sharpness: {
    id: 'sharpness',
    name: 'Sharpness',
    icon: '🧠',
    category: 'sharpness',
    tier: 1,
    color: '#3b82f6',
    bgClass: 'from-blue-400 to-blue-500',
    borderClass: 'border-blue-300',
    description: 'Pays attention and understands what is happening.',
    principle: 'Clarity begins with noticing what others overlook.',
    challenge: 'Explain one idea clearly.',
    pointsValue: 10,
    mergeResult: 'analyst',
    animationType: 'standard',
  },
  analyst: {
    id: 'analyst',
    name: 'Analyst',
    icon: '🔍',
    category: 'sharpness',
    tier: 2,
    color: '#1d4ed8',
    bgClass: 'from-blue-600 to-blue-700',
    borderClass: 'border-blue-500',
    description: 'Breaks information into useful parts.',
    principle: 'Understanding grows when you separate signal from noise.',
    challenge: 'Identify the cause of a current problem.',
    pointsValue: 25,
    mergeResult: 'strategist',
    animationType: 'standard',
  },
  strategist: {
    id: 'strategist',
    name: 'Strategist',
    icon: '♟️',
    category: 'sharpness',
    tier: 3,
    color: '#4f46e5',
    bgClass: 'from-indigo-500 to-indigo-600',
    borderClass: 'border-indigo-400',
    description: 'Sees connections between actions and outcomes.',
    principle: 'Every message should connect to a deliberate outcome.',
    challenge: 'Describe your goal in one sentence.',
    pointsValue: 50,
    mergeResult: 'visionary',
    animationType: 'standard',
  },
  visionary: {
    id: 'visionary',
    name: 'Visionary',
    icon: '🔮',
    category: 'sharpness',
    tier: 4,
    color: '#7c3aed',
    bgClass: 'from-purple-500 to-purple-600',
    borderClass: 'border-purple-400',
    description: 'Sees possibilities that others have not noticed.',
    principle: 'Great communicators paint futures people want to step into.',
    challenge: 'Describe a better future in one sentence.',
    pointsValue: 100,
    crossMergeRecipes: crossRecipes,
    animationType: 'standard',
  },
  enthusiasm: {
    id: 'enthusiasm',
    name: 'Enthusiasm',
    icon: '🔥',
    category: 'enthusiasm',
    tier: 1,
    color: '#f97316',
    bgClass: 'from-orange-400 to-orange-500',
    borderClass: 'border-orange-300',
    description: 'Communicates with visible energy and belief.',
    principle: 'Energy is contagious — belief shows in your voice.',
    challenge: 'Say what excites you about your goal.',
    pointsValue: 10,
    mergeResult: 'motivator',
    animationType: 'standard',
  },
  motivator: {
    id: 'motivator',
    name: 'Motivator',
    icon: '📣',
    category: 'enthusiasm',
    tier: 2,
    color: '#ea580c',
    bgClass: 'from-orange-600 to-orange-700',
    borderClass: 'border-orange-500',
    description: 'Helps people believe they can move forward.',
    principle: 'Encouragement turns hesitation into momentum.',
    challenge: 'Encourage someone using one sentence.',
    pointsValue: 25,
    mergeResult: 'influencer',
    animationType: 'standard',
  },
  influencer: {
    id: 'influencer',
    name: 'Influencer',
    icon: '🌟',
    category: 'enthusiasm',
    tier: 3,
    color: '#dc2626',
    bgClass: 'from-red-500 to-red-600',
    borderClass: 'border-red-400',
    description: 'Changes how people feel and think.',
    principle: 'Influence is the art of shifting perspective.',
    challenge: 'Make an ordinary idea sound exciting.',
    pointsValue: 50,
    mergeResult: 'catalyst',
    animationType: 'standard',
  },
  catalyst: {
    id: 'catalyst',
    name: 'Catalyst',
    icon: '⚡',
    category: 'enthusiasm',
    tier: 4,
    color: '#eab308',
    bgClass: 'from-yellow-400 to-amber-500',
    borderClass: 'border-yellow-300',
    description: 'Creates movement in people.',
    principle: "The best messages don't just inform — they compel action.",
    challenge: 'Convince someone to take action using one sentence.',
    pointsValue: 100,
    crossMergeRecipes: crossRecipes,
    animationType: 'cross-glow',
  },
  authority: {
    id: 'authority',
    name: 'Authority',
    icon: '👑',
    category: 'authority',
    tier: 1,
    color: '#22c55e',
    bgClass: 'from-green-400 to-green-500',
    borderClass: 'border-green-300',
    description: 'Speaks with certainty and direction.',
    principle: 'Confidence comes from knowing your direction.',
    challenge: 'Give one clear instruction.',
    pointsValue: 10,
    mergeResult: 'professional',
    animationType: 'standard',
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    icon: '💼',
    category: 'authority',
    tier: 2,
    color: '#15803d',
    bgClass: 'from-green-600 to-green-700',
    borderClass: 'border-green-500',
    description: 'Communicates with consistency and competence.',
    principle: 'Reliability builds trust over time.',
    challenge: 'Explain how you would solve a common problem.',
    pointsValue: 25,
    mergeResult: 'expert',
    animationType: 'standard',
  },
  expert: {
    id: 'expert',
    name: 'Expert',
    icon: '🎓',
    category: 'authority',
    tier: 3,
    color: '#10b981',
    bgClass: 'from-emerald-500 to-emerald-600',
    borderClass: 'border-emerald-400',
    description: 'Demonstrates specialized knowledge.',
    principle: 'Expertise earns the right to be heard.',
    challenge: 'Teach one useful principle in one sentence.',
    pointsValue: 50,
    mergeResult: 'master',
    animationType: 'standard',
  },
  master: {
    id: 'master',
    name: 'Master',
    icon: '🏆',
    category: 'authority',
    tier: 4,
    color: '#ca8a04',
    bgClass: 'from-amber-500 to-yellow-600',
    borderClass: 'border-amber-400',
    description: 'Leads through proven ability and experience.',
    principle: 'Mastery is demonstrated, not declared.',
    challenge: 'State a strong recommendation and explain why.',
    pointsValue: 100,
    crossMergeRecipes: crossRecipes,
    animationType: 'spotlight',
  },
  inspirational_leader: {
    id: 'inspirational_leader',
    name: 'Inspirational Leader',
    icon: '✨',
    category: 'cross',
    tier: 5,
    color: '#a855f7',
    bgClass: 'from-purple-500 via-amber-400 to-yellow-400',
    borderClass: 'border-purple-300',
    description: 'Combines powerful ideas with the energy to make people believe.',
    principle: 'Vision without energy stays invisible.',
    challenge: 'Share an idea that inspires immediate belief.',
    pointsValue: 250,
    animationType: 'cross-glow',
  },
  industry_icon: {
    id: 'industry_icon',
    name: 'Industry Icon',
    icon: '⭐',
    category: 'cross',
    tier: 5,
    color: '#ef4444',
    bgClass: 'from-red-500 via-emerald-500 to-amber-400',
    borderClass: 'border-amber-300',
    description: 'Combines influence, credibility, and visible mastery.',
    principle: 'Icons are built where impact meets integrity.',
    challenge: 'Describe what makes someone truly credible in your field.',
    pointsValue: 250,
    animationType: 'spotlight',
  },
  thought_leader: {
    id: 'thought_leader',
    name: 'Thought Leader',
    icon: '💡',
    category: 'cross',
    tier: 5,
    color: '#6366f1',
    bgClass: 'from-indigo-500 via-emerald-500 to-amber-400',
    borderClass: 'border-indigo-300',
    description: 'Combines original thinking with trusted expertise.',
    principle: 'Ideas gain power when backed by earned trust.',
    challenge: 'Share one original insight backed by experience.',
    pointsValue: 250,
    animationType: 'idea-particles',
  },
  legendary_communicator: {
    id: 'legendary_communicator',
    name: 'Legendary Communicator',
    icon: '👑',
    category: 'legendary',
    tier: 6,
    color: '#fbbf24',
    bgClass: 'from-amber-300 via-yellow-400 to-amber-500',
    borderClass: 'border-yellow-200',
    description:
      'Combines clarity, emotional power, and demonstrated authority into unforgettable communication.',
    principle: 'Legendary communicators make people think, feel, and act.',
    challenge: 'Deliver one message that is clear, emotionally powerful, and credible.',
    pointsValue: 1000,
    animationType: 'legendary',
  },
}

export const BASIC_TILE_IDS: TileId[] = ['sharpness', 'enthusiasm', 'authority']

export const ALL_TILE_IDS = Object.keys(TILES) as TileId[]

export const COLLECTION_SECTIONS = [
  { id: 'sharpness', title: 'Sharpness Path', tiles: ['sharpness', 'analyst', 'strategist', 'visionary'] as TileId[] },
  { id: 'enthusiasm', title: 'Enthusiasm Path', tiles: ['enthusiasm', 'motivator', 'influencer', 'catalyst'] as TileId[] },
  { id: 'authority', title: 'Authority Path', tiles: ['authority', 'professional', 'expert', 'master'] as TileId[] },
  {
    id: 'cross',
    title: 'Cross-Merge Archetypes',
    tiles: ['inspirational_leader', 'industry_icon', 'thought_leader'] as TileId[],
  },
  { id: 'legendary', title: 'Final Evolution', tiles: ['legendary_communicator'] as TileId[] },
]

export function getTile(id: TileId): TileConfig {
  return TILES[id]
}
